# CI Build number is incremental and not related to actual version number of the product
version: '{build}'

init:
  - git config --global core.autocrlf true

install:
  - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - ps: dnvm install 1.0.0-rc2-20221 -r clr -a x86 -u
  - ps: dnvm install 1.0.0-rc2-20221 -r clr -a x64 -u -p
  - ps: dnvm list
  
  # update project.json versions for continuous delivery to MyGet
  - ps: .\build-set-version.ps1

nuget:
  disable_publish_on_pr: true

## do we need this? platform: x64

configuration: Release

before_build:
  - ps: dnu restore

artifacts:
  - path: src\artifacts\bin\**\$(configuration)\*.nupkg
    name: NugetPackage

deploy:
  # publish all changes on master to MyGet
  - provider: Environment
    name: MyGet C3-OSS
  
  # new release tag -> create GitHub release
  - provider: GitHub
    release: $(appveyor_repo_tag_name)
    description: "See milestone for release notes"
    draft: true
    prerelease: true
    auth_token:
      secure: JU9H+A+WwAtz4Xkcd/50N239EiX1o7OpEnmtiQGayR+Zc2ZHF8xrcPMRelHyJwZL
    on:
      appveyor_repo_tag: true
